sudo: false
os:
  - linux
  - osx
jdk: oraclejdk1.8
language: android
matrix:
  include:
    - os: osx
      osx_image: xcode8.2
android:
  components:
    - build-tools-24.0.3
    - android-N
    - sys-img-armeabi-v7a-android-25
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - nvm install 6.10.2
  - nvm use 6.10.2
  - npm install -g cordova
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test:ios; fi
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - npm run test:android