sudo: false
os:
  - linux
  - osx
language:
  - android
  - objective-c
osx_image: xcode8.3
node_js:
  - "4"
  - "6"
script:
  - npm install -g cordova
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test:ios; fi
  - npm run test:android