image: Visual Studio 2015

environment:
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "6"

install:
  - npm install -g cordova
  - npm install

test_script:
  - npm run lint
  - npm run test:windows